#https://www.metoffice.gov.uk/services/data/datapoint/api-reference
import urllib.request
import json

APIkey = '940b74af-8410-4516-9326-e39b07de8cdd'

class API():
    """Interact with the Met Office API"""
    
    
    def __init__(self,key):
        self.key = key
        self.sites = self.get_sites_from_api()

    def api_connect(self, resource):
        """Connect to API and return json data.
        resource(str): URL for requesting information from API
        """
    
        baseurl = (f'http://datapoint.metoffice.gov.uk/public/data/{resource}'
                   f'key={self.key}')
        url = urllib.request.urlopen(baseurl)
        url_data = url.read().decode()
        data = json.loads(url_data)
        
        return data

    def get_sites_from_api(self):
        """Returns a list of all sites."""
        
        return self.api_connect('val/wxfcs/all/json/sitelist?')
    
            
    def get_timestamp(self):
        """Return all dates and times in a five day forcast"""
        
        timestamp = self.api_connect('val/wxfcs/all/json/capabilities?res'
                                     '=3hourly&')
        steps = timestamp['Resource']['TimeSteps']['TS']
        
        return [time for time in steps]

    def get_data_from_api(self, site_id):
        """Returns a list of lists containing dates, weather(code) and 
        temperature data for the given site id.
        site_id(str): Number generated by get_site_id_from_user_input function.
        """
        
        data = self.api_connect(f'val/wxfcs/all/json/{site_id}?res=3hourly&')
        filtered = data['SiteRep']['DV']['Location']['Period']
        codes = [data['Rep'] for data in filtered]
        dates = [data['value'] for data in filtered]
        temp = []
        weather = []
        for i in codes:
            temp_itr = [t['T'] for t in i]
            weather_itr = [w['W'] for w in i]
            temp.append(temp_itr)
            weather.append(weather_itr)
                        
        return [dates, temp, weather]
    
    
class ApiInteractions(API):
    """interacts with API class"""
    
    
    def get_site_id_from_user_input(self, user_input):
        """Matches user input with a site from the API and returns the site
        id for that location.
        user_input(str): A location in the UK.
        """        
        locations = self.sites['Locations']['Location']
        
        for values in locations:
            if values['name'] == user_input:
                return (values['id'])
            
    def api_data(self, user_input):
        """Return a list of date, temperature list and weather code list for 
        five days.
        user_input(str): Name of a location in the UK.     
        """
        
        siteid = self.get_site_id_from_user_input(user_input)
        api_data = self.get_data_from_api(siteid)
        data = self.split_lists(api_data, 5)
        
        return data

    def split_lists(self, lists, items):
        """Create a new list from a collection of lists where the nth item 
        in each list becomes a new list.
        lists(list)
        items(int): Number of elements in the lists.
        """
        
        new_list = []
        for num in range(items):
            for lst in lists:
                new_list.append(lst[num])
    
        return new_list